#!/bin/sh
#
# Start autodev
#

do_start() {
	echo "Starting module autoload..."
	echo /opt/sbin/autoload_modules > /proc/sys/kernel/hotplug
	/opt/sbin/autoload_modules
}

do_stop() {
	echo > /proc/sys/kernel/hotplug
}

case "$1" in
	start)
		do_start;
	;;
	stop)
		do_stop;
	;;
	restart|reload)
		do_stop;
		sleep 2;
		do_start;
	;;
	*)
		echo "Usage: $0 {start|restart|stop}"
		exit 1
esac

exit $?
